// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	postgres2 "github.com/gos0001/gomod-cryptopay/internal/adapter/postgres"
	"github.com/gos0001/gomod-cryptopay/internal/controller/http_v1"
	"github.com/gos0001/gomod-cryptopay/internal/invoicecfg"
	"github.com/gos0001/gomod-cryptopay/internal/middleware"
	"github.com/gos0001/gomod-cryptopay/internal/orchestrator/bootstrap"
	"github.com/gos0001/gomod-cryptopay/internal/orchestrator/cron"
	"github.com/gos0001/gomod-cryptopay/internal/service/matching"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/assets/asset_list"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/assets/asset_seeder"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/chain/bsc_watcher"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/chain/tron_watcher"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/invoices/invoice_cancel"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/invoices/invoice_create"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/invoices/invoice_expirer"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/invoices/invoice_get"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/invoices/invoice_list"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/notify/webhook_dispatcher"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/payments/orphan_list"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/sys/schema_ensure"
	"github.com/gos0001/gomod-cryptopay/internal/usecases/sys/sys_health"
	"github.com/gos0001/gomod-cryptopay/pkg/config"
	"github.com/gos0001/gomod-cryptopay/pkg/dbschema"
	"github.com/gos0001/gomod-cryptopay/pkg/evm"
	"github.com/gos0001/gomod-cryptopay/pkg/logger"
	"github.com/gos0001/gomod-cryptopay/pkg/postgres"
	"github.com/gos0001/gomod-cryptopay/pkg/tron"
	"github.com/gos0001/gomod-cryptopay/pkg/webhook"
	"github.com/gos0001/gomod-cryptopay/schema"
)

// Injectors from wire.go:

// InitializeApp takes the configuration path rather than reading it from the
// environment. config.Path is a named type because wire resolves by type alone,
// and a bare string would collide with every other string in the graph.
func InitializeApp(configPath config.Path) (*App, error) {
	file, err := config.Load(configPath)
	if err != nil {
		return nil, err
	}
	loggerConfig, err := logger.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	sugaredLogger, err := logger.New(loggerConfig)
	if err != nil {
		return nil, err
	}
	middlewareConfig, err := middleware.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	middlewareMiddleware := middleware.New(middlewareConfig)
	postgresConfig, err := postgres.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	pool, err := postgres.New(postgresConfig)
	if err != nil {
		return nil, err
	}
	adapter := postgres2.New(pool)
	usecase := sys_health.New(adapter)
	httPv1 := sys_health.NewHTTPv1(usecase)
	invoicecfgConfig, err := invoicecfg.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	invoice_createUsecase := invoice_create.New(adapter, invoicecfgConfig)
	invoice_createHTTPv1 := invoice_create.NewHTTPv1(invoice_createUsecase, sugaredLogger)
	invoice_listUsecase := invoice_list.New(adapter)
	invoice_listHTTPv1 := invoice_list.NewHTTPv1(invoice_listUsecase, sugaredLogger)
	invoice_getUsecase := invoice_get.New(adapter)
	invoice_getHTTPv1 := invoice_get.NewHTTPv1(invoice_getUsecase, sugaredLogger)
	invoice_cancelUsecase := invoice_cancel.New(adapter, invoicecfgConfig)
	invoice_cancelHTTPv1 := invoice_cancel.NewHTTPv1(invoice_cancelUsecase, sugaredLogger)
	asset_listUsecase := asset_list.New(adapter)
	asset_listHTTPv1 := asset_list.NewHTTPv1(asset_listUsecase, sugaredLogger)
	orphan_listUsecase := orphan_list.New(adapter)
	orphan_listHTTPv1 := orphan_list.NewHTTPv1(orphan_listUsecase, sugaredLogger)
	engine := http_v1.New(middlewareMiddleware, httPv1, invoice_createHTTPv1, invoice_listHTTPv1, invoice_getHTTPv1, invoice_cancelHTTPv1, asset_listHTTPv1, orphan_listHTTPv1)
	mainConfig, err := LoadConfig(file)
	if err != nil {
		return nil, err
	}
	bootstrapConfig, err := bootstrap.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	definition := schema.Definition()
	dbschemaConfig, err := dbschema.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	applier := dbschema.New(pool, definition, dbschemaConfig)
	schema_ensureUsecase := schema_ensure.New(applier, sugaredLogger)
	schema_ensureBootstrap := schema_ensure.NewBootstrap(schema_ensureUsecase)
	asset_seederConfig, err := asset_seeder.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	asset_seederUsecase := asset_seeder.New(adapter, asset_seederConfig, sugaredLogger)
	asset_seederBootstrap := asset_seeder.NewBootstrap(asset_seederUsecase, sugaredLogger)
	bootstrapBootstrap := bootstrap.New(sugaredLogger, bootstrapConfig, schema_ensureBootstrap, asset_seederBootstrap)
	cronConfig, err := cron.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	invoice_expirerUsecase := invoice_expirer.New(adapter, invoicecfgConfig, sugaredLogger)
	invoice_expirerCron := invoice_expirer.NewCron(invoice_expirerUsecase, invoicecfgConfig)
	tronConfig, err := tron.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	client := tron.New(tronConfig)
	webhookConfig, err := webhook.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	sender := webhook.New(webhookConfig)
	service := matching.New(adapter, invoicecfgConfig, sender, sugaredLogger)
	tron_watcherConfig, err := tron_watcher.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	tron_watcherUsecase := tron_watcher.New(client, service, adapter, tron_watcherConfig, invoicecfgConfig, sugaredLogger)
	tron_watcherCron := tron_watcher.NewCron(tron_watcherUsecase, tron_watcherConfig)
	evmConfig, err := evm.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	evmClient, err := evm.New(evmConfig)
	if err != nil {
		return nil, err
	}
	bsc_watcherConfig, err := bsc_watcher.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	bsc_watcherUsecase := bsc_watcher.New(evmClient, service, adapter, bsc_watcherConfig, invoicecfgConfig, sugaredLogger)
	bsc_watcherCron := bsc_watcher.NewCron(bsc_watcherUsecase, bsc_watcherConfig)
	webhook_dispatcherConfig, err := webhook_dispatcher.LoadConfig(file)
	if err != nil {
		return nil, err
	}
	webhook_dispatcherUsecase := webhook_dispatcher.New(adapter, sender, webhook_dispatcherConfig, sugaredLogger)
	webhook_dispatcherCron := webhook_dispatcher.NewCron(webhook_dispatcherUsecase, webhook_dispatcherConfig)
	cronCron := cron.New(sugaredLogger, cronConfig, invoice_expirerCron, tron_watcherCron, bsc_watcherCron, webhook_dispatcherCron)
	app := NewApp(sugaredLogger, engine, mainConfig, bootstrapBootstrap, cronCron, pool, file)
	return app, nil
}
